version: '3'
services:
  db:
    image: 'postgres:alpine'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'platzi'
      POSTGRES_DB: 'platzi-market'
    volumes:
      - db-data:/var/lib/postgresql/data/
      # - ./db:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:4.22
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '64374:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
  web:
    build: .
    expose:
      - "8091"
    depends_on:
      - db
volumes:
  db-data:
  pgadmin-data:
